app: Bike
-
move up: key(ctrl-cmd-up)
move down: key(ctrl-cmd-down)
drill in: key(alt-cmd-right)
drill out: key(alt-cmd-left)
indent: key(tab)
dedent: key(shift-tab)
collapsing: key(cmd-9)
expanding: key(cmd-0)
collapse all: key(ctrl-cmd-9)
expand all: key(ctrl-cmd-0)
focusing: key(alt-cmd-f)
typewriter: key(alt-cmd-t)
table: key(ctrl-shift-tab)
tabber | tipsy: key(ctrl-tab)
typewriter: key(alt-cmd-t)